INSERT INTO Categoria (Id, Nombre) VALUES ('1', 'Monitores');
INSERT INTO Categoria (Id, Nombre) VALUES ('2', 'Teclados');
INSERT INTO Categoria (Id, Nombre) VALUES ('3', 'Mouse');
INSERT INTO Categoria (Id, Nombre) VALUES ('4', 'Auriculares');
INSERT INTO Categoria (Id, Nombre) VALUES ('5', 'Notebooks');
INSERT INTO Categoria (Id, Nombre) VALUES ('6', 'Procesadores');
INSERT INTO Categoria (Id, Nombre) VALUES ('7', 'Placas de video');
INSERT INTO Categoria (Id, Nombre) VALUES ('8', 'Memorias RAM');
INSERT INTO Categoria (Id, Nombre) VALUES ('9', 'Discos SSD');
INSERT INTO Categoria (Id, Nombre) VALUES ('10', 'Fuentes');