INSERT INTO Proveedor (Id, Nombre, Contacto) VALUES ('1', 'TechCorp', 'ventas@techcorp.com');
INSERT INTO Proveedor (Id, Nombre, Contacto) VALUES ('2', 'HardPlus', 'info@hardplus.com');
INSERT INTO Proveedor (Id, Nombre, Contacto) VALUES ('3', 'CompuMax', 'contacto@compumax.com');
INSERT INTO Proveedor (Id, Nombre, Contacto) VALUES ('4', 'DigitalStore', 'ventas@digital.com');
INSERT INTO Proveedor (Id, Nombre, Contacto) VALUES ('5', 'PC Mayorista', 'mayorista@pc.com');
INSERT INTO Proveedor (Id, Nombre, Contacto) VALUES ('6', 'InsumosNet', 'info@insumosnet.com');
INSERT INTO Proveedor (Id, Nombre, Contacto) VALUES ('7', 'TecnoWorld', 'ventas@tecnoworld.com');
INSERT INTO Proveedor (Id, Nombre, Contacto) VALUES ('8', 'Hardware SA', 'contacto@hardware.com');
INSERT INTO Proveedor (Id, Nombre, Contacto) VALUES ('9', 'ElectroParts', 'ventas@eparts.com');
INSERT INTO Proveedor (Id, Nombre, Contacto) VALUES ('10', 'MegaTech', 'info@megatech.com');